//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.TestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestService.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsoleApp1.TestService.HelloWorldResponse HelloWorld(ConsoleApp1.TestService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.TestService.HelloWorldResponse> HelloWorldAsync(ConsoleApp1.TestService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AliResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ali", ReplyAction="*")]
        ConsoleApp1.TestService.AliResponse Ali(ConsoleApp1.TestService.AliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ali", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.TestService.AliResponse> AliAsync(ConsoleApp1.TestService.AliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        int Sum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dev", ReplyAction="*")]
        int Dev(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dev", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DevAsync(int x, int y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.TestService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleApp1.TestService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.TestService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleApp1.TestService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AliRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ali", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.TestService.AliRequestBody Body;
        
        public AliRequest() {
        }
        
        public AliRequest(ConsoleApp1.TestService.AliRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AliRequestBody {
        
        public AliRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AliResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AliResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.TestService.AliResponseBody Body;
        
        public AliResponse() {
        }
        
        public AliResponse(ConsoleApp1.TestService.AliResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AliResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AliResult;
        
        public AliResponseBody() {
        }
        
        public AliResponseBody(string AliResult) {
            this.AliResult = AliResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : ConsoleApp1.TestService.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApp1.TestService.MyWebServiceSoap>, ConsoleApp1.TestService.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.TestService.HelloWorldResponse ConsoleApp1.TestService.MyWebServiceSoap.HelloWorld(ConsoleApp1.TestService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleApp1.TestService.HelloWorldRequest inValue = new ConsoleApp1.TestService.HelloWorldRequest();
            inValue.Body = new ConsoleApp1.TestService.HelloWorldRequestBody();
            ConsoleApp1.TestService.HelloWorldResponse retVal = ((ConsoleApp1.TestService.MyWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.TestService.HelloWorldResponse> ConsoleApp1.TestService.MyWebServiceSoap.HelloWorldAsync(ConsoleApp1.TestService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.TestService.HelloWorldResponse> HelloWorldAsync() {
            ConsoleApp1.TestService.HelloWorldRequest inValue = new ConsoleApp1.TestService.HelloWorldRequest();
            inValue.Body = new ConsoleApp1.TestService.HelloWorldRequestBody();
            return ((ConsoleApp1.TestService.MyWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.TestService.AliResponse ConsoleApp1.TestService.MyWebServiceSoap.Ali(ConsoleApp1.TestService.AliRequest request) {
            return base.Channel.Ali(request);
        }
        
        public string Ali() {
            ConsoleApp1.TestService.AliRequest inValue = new ConsoleApp1.TestService.AliRequest();
            inValue.Body = new ConsoleApp1.TestService.AliRequestBody();
            ConsoleApp1.TestService.AliResponse retVal = ((ConsoleApp1.TestService.MyWebServiceSoap)(this)).Ali(inValue);
            return retVal.Body.AliResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.TestService.AliResponse> ConsoleApp1.TestService.MyWebServiceSoap.AliAsync(ConsoleApp1.TestService.AliRequest request) {
            return base.Channel.AliAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.TestService.AliResponse> AliAsync() {
            ConsoleApp1.TestService.AliRequest inValue = new ConsoleApp1.TestService.AliRequest();
            inValue.Body = new ConsoleApp1.TestService.AliRequestBody();
            return ((ConsoleApp1.TestService.MyWebServiceSoap)(this)).AliAsync(inValue);
        }
        
        public int Sum() {
            return base.Channel.Sum();
        }
        
        public System.Threading.Tasks.Task<int> SumAsync() {
            return base.Channel.SumAsync();
        }
        
        public int Dev(int x, int y) {
            return base.Channel.Dev(x, y);
        }
        
        public System.Threading.Tasks.Task<int> DevAsync(int x, int y) {
            return base.Channel.DevAsync(x, y);
        }
    }
}
